version: 2
updates:
  # ── Python (Poetry-managed) ────────────────────────────────────────────────
  - package-ecosystem: "pip"
    directory: "/" # looks at pyproject.toml / poetry.lock
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    insecure-external-code-execution: "deny"
    commit-message:
      prefix: "[DEPS] "
    # ignore gigantic breaking bumps unless we choose otherwise
    # ignore:
    #   - dependency-name: "boto3"
    #     update-types: ["version-update:semver-major"]

  # ── GitHub Actions versions ───────────────────────────────────────────────
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[DEPS] "
